/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    'tournamentState': MotiaStream<unknown>
    'gameState': MotiaStream<unknown>
  }

  interface Handlers {
    'ServeGameJS': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'ServeGameHTML': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'ServeGameCSS': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'TournamentMatchStart': EventHandler<unknown, { topic: 'game.move.request'; data: unknown }>
    'TournamentMatchCompleted': EventHandler<unknown, { topic: 'tournament.match.start'; data: unknown } | { topic: 'tournament.completed'; data: unknown }>
    'TournamentCompleted': EventHandler<unknown, never>
    'ProcessAIMove': EventHandler<unknown, { topic: 'game.move.request'; data: unknown } | { topic: 'game.completed'; data: unknown } | { topic: 'tournament.match.completed'; data: unknown }>
    'GameCompleted': EventHandler<unknown, never>
    'StartTournament': ApiRouteHandler<unknown, ApiResponse<200, unknown> | ApiResponse<400, unknown> | ApiResponse<404, unknown>, { topic: 'tournament.match.start'; data: unknown }>
    'ListModels': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, unknown>, never>
    'GetTournament': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, unknown> | ApiResponse<404, unknown>, never>
    'GetGame': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, unknown> | ApiResponse<404, unknown>, never>
    'CreateTournament': ApiRouteHandler<unknown, ApiResponse<201, unknown> | ApiResponse<400, unknown>, never>
    'CreateGame': ApiRouteHandler<unknown, ApiResponse<201, unknown> | ApiResponse<400, unknown>, { topic: 'game.move.request'; data: unknown }>
  }
    
}