/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'NotionUpdatePage': EventHandler<unknown, never>
    'NotionCreatePage': EventHandler<unknown, never>
    'NotionArchivePage': EventHandler<unknown, never>
    'NotionAddComment': EventHandler<unknown, never>
    'GitHubWebhook': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'notion-create-page'; data: unknown } | { topic: 'notion-update-page'; data: unknown } | { topic: 'notion-archive-page'; data: unknown } | { topic: 'notion-add-comment'; data: unknown }>
  }
    
}